# Generated by Django 5.1.2 on 2024-11-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_ticket_quantity_alter_refundrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=1, upload_to='event_images/'),
            preserve_default=False,
        ),
    ]
