# Generated by Django 5.1.2 on 2024-11-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_event_created_by_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profile/1.png', upload_to='images/profile/'),
        ),
    ]
