# Generated by Django 5.1.2 on 2024-11-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default='2024-12-06'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default='20:45:00'),
        ),
    ]
