# Generated by Django 5.1.2 on 2024-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ticket',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='tickets',
            field=models.ManyToManyField(to='pages.ticket'),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Sadad', 'Sadad'), ('Edfa3li', 'Edfa3li')], max_length=50),
        ),
    ]
