# Generated by Django 5.1.3 on 2024-12-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_refundrequest_status_alter_user_role_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisherprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='siteadminprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='PublisherProfile',
        ),
        migrations.DeleteModel(
            name='SiteAdminProfile',
        ),
    ]
