# Generated by Django 5.1.3 on 2024-12-16 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_publisherprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='purchase_date',
            new_name='reserved_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='quantity',
        ),
        migrations.AddField(
            model_name='event',
            name='publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_reserved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
