# Generated by Django 5.1.3 on 2024-12-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_rename_purchase_date_ticket_reserved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tickets_sold',
        ),
    ]
